### ISSUE TITLE
Build failure: com.helger:ph-cli:jar:2.0.0-SNAPSHOT is missing

### ISSUE THREAD

**Issue by fdev** [phax/phoss-validator#1]
Since the cli params were added I'm unable to build the project.

```
[WARNING] The POM for com.helger:ph-cli:jar:2.0.0-SNAPSHOT is missing, no dependency information available
```

**Comment by phax** [comment]
Work in progress - Travis build on ph-cli fails currently. During the day :)

**Comment by phax** [comment]
Found the issue - ph-cli SNAPSHOTs were not uploaded to Central staging - fixed.
And btw. release 2.0.0 is on its way to Maven Central - pom is updated afterwards.
thanks for pointing this out.

**Comment by fdev** [comment]
Thank you for fixing this so quickly! :+1:
